let a = null
        console.log('this is null => ' + a)
        let b = 1234
        console.log('this is number => ' + b)
      /*   const sym3 = Symbol("foo");//To create a new primitive Symbol, you write Symbol() with an optional string as its description
        console.log('symbol=> ' + sym3) */
        let string = 'hello world!'
        console.log('string => ' + string)
        let x = ''
        console.log('undefiend => ' + x)
        let y = true
        console.log('boolean true or false => ' + y)
        const bigNumber = BigInt("123456789012345678901234567890");
        console.log('bigint => '+bigNumber);